import type { Metadata } from 'next';
import './globals.css';
import MantineProvider from '@/components/MantineProvider';
import { ColorSchemeScript } from '@mantine/core';
import StoreProvider from './storeProvider';

export const metadata: Metadata = {
  title: `Tri's Next.js App`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body>
        <StoreProvider>
          <ColorSchemeScript />
          <MantineProvider>{children}</MantineProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
